### ISSUE TITLE
Check visual studio/git on windows

### ISSUE THREAD

**Issue by murraycadzow** [mikblack/ga-workshop-tutorial#3]
Need to check if the install instructions for visual studio and the git integration require any additional steps for windows

**Comment by mikblack** [comment]
Thanks Murray - can you switch over to the GA repo for this now:

https://github.com/GenomicsAotearoa/ga-workshop-tutorial

Sorry, I should have pinged you when I forked things yesterday.

**Comment by murraycadzow** [comment]
Hi Mik,
Thanks, saw that.

Not entirely sure why, but because the ga version is forked from this one it doesn't have the option for issues (or it might just be my access on it - unsure) - the issue was just for me to follow up on
